const men=[
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/8/z/4/6-mrj2016-6-aadi-white-parrot-original-imagkjy5hed6qd9r.jpeg?q=70",
        brand: "aadi",
        price: " RS.399",
        description: "Casuals For Men",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/7/f/p/10-abacus-10-density-c-green-original-imaghdh37ghtbffr.jpeg?q=70",
        brand: "Density",
        price: "RS.839",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/k/n/7/-original-imaggcb7k3frtbrk.jpeg?q=70",
        brand: "Sparx",
        price: "RS.1239",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 4,
        image: "https://rukminim1.flixcart.com/image/612/612/l4ssfww0/shoe/s/i/l/10-2031-blu-wht-44-bruton-blue-original-imagfmdubtgj8ebj.jpeg?q=70",
        brand: "Bruton",
        price: "RS.359",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/1/f/6-11g-787-6-campus-wht-sil-b-org-original-imaghycd7arhuqk9.jpeg?q=70",
        brand: "Campus",
        price: "RS.1399",
        description: "Casuals For Men",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/r/f/-original-imagg3a78xj9z8zf.jpeg?q=70",
        brand: "TR",
        price: " RS.449",
        description: "Synthetic Leather For Men",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/q/c/-original-imagg4zg8xswmhhv.jpeg?q=70",
        brand: "Bata",
        price: "RS.899",
        description: "Formals for men",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/q/h/z/7-mrj1852-7-aadi-black-original-imagdwgudezandfs-bb.jpeg?q=70",
        brand: "aadi",
        price: "RS.479",
        description: "Oxford For Men",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/k63xle80/shoe/9/a/p/krf1133-7-kreuzer-black-original-imafeng3jwnrwgry.jpeg?q=70",
        brand: "Kirasa",
        price: "RS.499",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/kzhbfrk0/shoe/y/m/k/9-mrj1851-9-aadi-tan-original-imagbgnfvgdhwwc4.jpeg?q=70",
        brand: "aadi",
        price: "RS.399",
        description: "Formals for men",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/o/t/-original-imagg4zgnumghec2.jpeg?q=70",
        brand: "Onivixo",
        price: "RS.499",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/i/l/-original-imaggjtrfhv5fjbq.jpeg?q=70",
        brand: "Krors",
        price: "RS.499",
        description: "Ethnic Mule For Men",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/q/6/-original-imagg3a8yppvrvhs.jpeg?q=70",
        brand: "Vellinto",
        price: "RS.623",
        description: "Mojaris For Men",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/ksyz8280/shoe/w/6/n/8-jalsa-jt38-8-jaipur-trendcraft-white-original-imag6eskx7ubpeq6.jpeg?q=70",
        brand: "Jaipur Trend Craft",
        price: "RS.369",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/h/z/-original-imaggcaxwzpheakm.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "Oxford For Men",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/l4n2oi80/shoe/p/j/q/9-art-mn9-knight-walkers-brown-original-imagfh6nz3zyfsds.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "Synthetic Leather For Men",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/kxc5nrk0/shoe/g/n/q/8-mrj1796-8-aadi-black-original-imag9tcewzsbedmv.jpeg?q=70",
        brand: "aadi",
        price: "RS.359",
        description: "Formals for men",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/l/l/-original-imagfpz8fgbmwgzt-bb.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/9/u/rkm-10-feetway-black-original-imafpzunrvnbnhwd-bb.jpeg?q=70",
        brand: "Feetway",
        price: "RS.616",
        description: "Oxford For Men",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/g/k/6-54490051-6-liberty-black-original-imaghj7ecggwrjsb.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Formals for men",
    },
    {
        id: 21,
        image: "https://rukminim1.flixcart.com/image/612/612/k3xcdjk0pkrrdj/shoe/4/h/c/8-orifwsh-1237-oricum-orifwsh-1237-original-imafgfuyxhhfczxx.jpeg?q=70",
        brand: "Bersache",
        price: "RS.438",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 22,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/a/m/n/-original-imagg6r9cqyhjvzw.jpeg?q=70",
        brand: "Bata",
        price: "RS.848",
        description: "Synthetic Leather For Men",
    },
    {
        id: 23,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/i/e/-original-imaghvb57ftpkfxb.jpeg?q=70",
        brand: "Provogue",
        price: "RS.969",
        description: "Formals for men",
    },
    {
        id: 24,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/l/n/-original-imagg7syze82egzu.jpeg?q=70",
        brand: "TR",
        price: "RS.479",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 25,
        image: "https://rukminim1.flixcart.com/image/612/612/l52sivk0/shoe/s/2/r/8-719-8-ovexa-tan-original-imagfu3mbhdyzpgn.jpeg?q=70",
        brand: "putul",
        price: "RS.499",
        description: "Mojaris For Men",
    },
    {
        id: 26,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/3/4/4/1048-9-dev-fashion-hub-black-original-imaew7pfknkkdsxr-bb.jpeg?q=70",
        brand: "Prem",
        price: "RS.260",
        description: "Royal and Traditional",
    },
    {
        id: 27,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/y/z/n/-original-imaghvbanp2nwjgj.jpeg?q=70",
        brand: "Jayman",
        price: "RS.299",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 28,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/z/n/-original-imagg5qa7bcm83qm.jpeg?q=70",
        brand: "kavsun",
        price: "RS.699",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 29,
        image: "https://rukminim1.flixcart.com/image/612/612/k3dc7m80pkrrdj/shoe/q/a/m/6-mrj1303-aadi-original-imafhvrh2c8uxfgw.jpeg?q=70",
        brand: "aadi",
        price: "RS.499",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 30,
        image: "https://rukminim1.flixcart.com/image/612/612/kfwvcsw0-0/shoe/i/i/4/mrj1488-10-aadi-black-original-imafw9p38fqvmmmh.jpeg?q=70",
        brand: "aadi",
        price: "RS.329",
        description: "Synthetic Leather For Men",
    },
    {
        id: 31,
        image: "https://rukminim1.flixcart.com/image/612/612/k4hcjgw0pkrrdj/shoe/8/j/5/7-orifwsh-3029-oricum-orifwsh-3029-original-imafj8sxft7g2gyh.jpeg?q=70",
        brand: "Oriculum",
        price: "RS.479",
        description: "Formals for men",
    },
    {
        id: 32,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/5/i/z/-original-imagg6r4whwwphpu.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 33,
        image: "https://rukminim1.flixcart.com/image/612/612/kx3l0nk0/shoe/d/h/3/6-8214478-6-bata-brown-original-imag9mz3z722mvvt.jpeg?q=70",
        brand: "Bata",
        price: "RS.1349",
        description: "Formals for men",
    },
    {
        id: 34,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/n/p/-original-imaggcaxf8g4hff3.jpeg?q=70",
        brand: "aadi",
        price: "RS.449",
        description: "Synthetic Leather For Men",
    },
    {
        id: 35,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/d/i/7-95000215-41-roamra-white-original-imag4ahytjmqdzz8-bb.jpeg?q=70",
        brand: "Bersache",
        price: "RS.1349",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 36,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/t/v/10-6g-842-10-campus-d-gry-blk-original-imag7j7yefur495y-bb.jpeg?q=70",
        brand: "Campus",
        price: "RS.999",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 37,
        image: "https://rukminim1.flixcart.com/image/612/612/ku8pbbk0/shoe/d/b/g/6-mrj1241-aadi-black-original-imag7egwqteqdc5d.jpeg?q=70",
        brand: "aadi",
        price: "RS.499",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 38,
        image: "https://rukminim1.flixcart.com/image/612/612/l1whaq80/shoe/t/v/k/8-rso202-red-tape-grey-original-imagdcxyz94c23bh.jpeg?q=70",
        brand: "Redtape",
        price: "RS.1699",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 39,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/n/8/-original-imaggcaxumgswcfy.jpeg?q=70",
        brand: "Asain",
        price: "RS.329",
        description: "Casuals For Men",
    },
    {
        id: 40,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/v/9/8-advnchr-42-nobelite-grey-original-imagct5485hm2ckd-bb.jpeg?q=70",
        brand: "Nobelite",
        price: "RS.374",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 41,
        image: "https://rukminim1.flixcart.com/image/612/612/ks243gw0/shoe/0/a/i/7-8050-black-green-waan-black-green-original-imag5pswqe6r6gyj.jpeg?q=70",
        brand: "Waan",
        price: "RS.599",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 42,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/w/0/9-22g-574-campus-blk-wht-original-imaghg6qukqpxtge.jpeg?q=70",
        brand: "Campus",
        price: "RS.719",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 43,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/w/t/-original-imaggcb5gcgzctaq.jpeg?q=70",
        brand: "Bruton",
        price: "RS.389",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 44,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/a/k/j/-original-imagg5r9zmzhh27g.jpeg?q=70",
        brand: "Bruton",
        price: "RS.259",
        description: "Casuals For Men",
    },
    {
        id: 45,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/p/d/z/-original-imagg6rftp5pktbx.jpeg?q=70",
        brand: "Beerock",
        price: "RS.569",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 46,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/1/m/7-9326-7-world-wear-footwear-yellow-original-imaggp5exfvgcacx.jpeg?q=70",
        brand: "World Wear Footwear",
        price: "RS.299",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 47,
        image: "https://rukminim1.flixcart.com/image/612/612/klwmufk0/shoe/9/r/p/6-cb-489-502-6-chevit-black-original-imagyx9jzwgzatzg.jpeg?q=70",
        brand: "Chevit",
        price: "RS.599",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 48,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/8/s/f/7-rockey-7-magnolia-white-original-imaggutpr7zeeffu.jpeg?q=70",
        brand: "Mangolia",
        price: "RS.454",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 49,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/1/w/7-brd-806-7-birde-white-original-imagghggmu3ncgsr.jpeg?q=70",
        brand: "Bride",
        price: "RS.599",
        description: "Casuals For Men",
    },
    {
        id: 50,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/x/8/-original-imagg7ek9cjf2tmz.jpeg?q=70",
        brand: "Vellinto",
        price: " RS.623",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 51,
        image: "https://rukminim1.flixcart.com/image/612/612/kg2l47k0-0/shoe/d/q/2/550w-6-baxxico-white-original-imafwdy5u7fdnm9j.jpeg?q=70",
        brand: "Yayab",
        price: "RS.899",
        description: "Mojaris For Men",
    },
    {
        id: 52,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/t/i/-original-imaggdfegjgckdub.jpeg?q=70",
        brand: "Ryag",
        price: "RS.479",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 53,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/3/f/y/j3-7-sarthi-brown-original-imaf5s6axhqw6kgw-bb.jpeg?q=70",
        brand: "Shathi",
        price: "RS.499",
        description: "Royal and Traditional",
    },
    {
        id: 54,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/0/v/8-art-ca306-vellinto-brown-original-imagka2ekenxw3y8.jpeg?q=70",
        brand: "Vellinto",
        price: "RS.399",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 55,
        image: "https://rukminim1.flixcart.com/image/612/612/l12h1u80/shoe/j/r/s/7-oak1-7-hyooo-brown-original-imagcpv7gzbrnzj4.jpeg?q=70",
        brand: "hyoo",
        price: "RS.799",
        description: "Ethnic Mule For Men",
    },
    {
        id: 56,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/t/h/6-art-ca159-vellinto-tan-original-imagykfz57fyvkgk-bb.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 57,
        image: "https://rukminim1.flixcart.com/image/612/612/l5iid8w0/shoe/j/k/6/8-55800521-rockfield-brown-original-imagg62cakybybxk.jpeg?q=70",
        brand: "Rockfield",
        price: "RS.359",
        description: "Royal and Traditional",
    },
    {
        id: 58,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/f/n/9-kv319-kavsun-brown-original-imagh2tqzbhvzqf5.jpeg?q=70",
        brand: "Kavsun",
        price: "RS.699",
        description: "Mojaris For Men",
    },
    {
        id: 59,
        image: "https://rukminim1.flixcart.com/image/612/612/l19m93k0/shoe/p/k/z/9-white-chain-traditional-funda-white-original-imagcvc9unqvkw64.jpeg?q=70",
        brand: "Taditional Funda",
        price: "RS.499",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 60,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/j/3/7/6-yb587-6-6-yb-bazaar-beige-original-imaghafbghav9fyb.jpeg?q=70",
        brand: "YB Bazaar",
        price: "RS.299",
        description: "Mojaris For Men",
    },
]

const CasualMen = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/8/z/4/6-mrj2016-6-aadi-white-parrot-original-imagkjy5hed6qd9r.jpeg?q=70",
        brand: "aadi",
        price: " RS.399",
        description: "Casuals For Men",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/7/f/p/10-abacus-10-density-c-green-original-imaghdh37ghtbffr.jpeg?q=70",
        brand: "Density",
        price: "RS.839",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/k/n/7/-original-imaggcb7k3frtbrk.jpeg?q=70",
        brand: "Sparx",
        price: "RS.1239",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 4,
        image: "https://rukminim1.flixcart.com/image/612/612/l4ssfww0/shoe/s/i/l/10-2031-blu-wht-44-bruton-blue-original-imagfmdubtgj8ebj.jpeg?q=70",
        brand: "Bruton",
        price: "RS.359",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/1/f/6-11g-787-6-campus-wht-sil-b-org-original-imaghycd7arhuqk9.jpeg?q=70",
        brand: "Campus",
        price: "RS.1399",
        description: "Casuals For Men",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/d/i/7-95000215-41-roamra-white-original-imag4ahytjmqdzz8-bb.jpeg?q=70",
        brand: "Bersache",
        price: "RS.1349",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/t/v/10-6g-842-10-campus-d-gry-blk-original-imag7j7yefur495y-bb.jpeg?q=70",
        brand: "Campus",
        price: "RS.999",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/ku8pbbk0/shoe/d/b/g/6-mrj1241-aadi-black-original-imag7egwqteqdc5d.jpeg?q=70",
        brand: "aadi",
        price: "RS.499",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/l1whaq80/shoe/t/v/k/8-rso202-red-tape-grey-original-imagdcxyz94c23bh.jpeg?q=70",
        brand: "Redtape",
        price: "RS.1699",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/n/8/-original-imaggcaxumgswcfy.jpeg?q=70",
        brand: "Asain",
        price: "RS.329",
        description: "Casuals For Men",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/v/9/8-advnchr-42-nobelite-grey-original-imagct5485hm2ckd-bb.jpeg?q=70",
        brand: "Nobelite",
        price: "RS.374",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/ks243gw0/shoe/0/a/i/7-8050-black-green-waan-black-green-original-imag5pswqe6r6gyj.jpeg?q=70",
        brand: "Waan",
        price: "RS.599",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/w/0/9-22g-574-campus-blk-wht-original-imaghg6qukqpxtge.jpeg?q=70",
        brand: "Campus",
        price: "RS.719",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/w/t/-original-imaggcb5gcgzctaq.jpeg?q=70",
        brand: "Bruton",
        price: "RS.389",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/a/k/j/-original-imagg5r9zmzhh27g.jpeg?q=70",
        brand: "Bruton",
        price: "RS.259",
        description: "Casuals For Men",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/p/d/z/-original-imagg6rftp5pktbx.jpeg?q=70",
        brand: "Beerock",
        price: "RS.569",
        description: "Wild Rider Layers Sn",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/1/m/7-9326-7-world-wear-footwear-yellow-original-imaggp5exfvgcacx.jpeg?q=70",
        brand: "World Wear Footwear",
        price: "RS.299",
        description: "Mirage Sport Tech Sneakers For Men",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/klwmufk0/shoe/9/r/p/6-cb-489-502-6-chevit-black-original-imagyx9jzwgzatzg.jpeg?q=70",
        brand: "Chevit",
        price: "RS.599",
        description: "Nature X One DARK OLIVE Casuals For Men",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/8/s/f/7-rockey-7-magnolia-white-original-imaggutpr7zeeffu.jpeg?q=70",
        brand: "Mangolia",
        price: "RS.454",
        description: "ZX 2K BOOST 2.0 Casuals For ",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/1/w/7-brd-806-7-birde-white-original-imagghggmu3ncgsr.jpeg?q=70",
        brand: "Bride",
        price: "RS.599",
        description: "Casuals For Men",
    },
]

const FormalMen = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/r/f/-original-imagg3a78xj9z8zf.jpeg?q=70",
        brand: "TR",
        price: " RS.449",
        description: "Synthetic Leather For Men",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/q/c/-original-imagg4zg8xswmhhv.jpeg?q=70",
        brand: "Bata",
        price: "RS.899",
        description: "Formals for men",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/q/h/z/7-mrj1852-7-aadi-black-original-imagdwgudezandfs-bb.jpeg?q=70",
        brand: "aadi",
        price: "RS.479",
        description: "Oxford For Men",
    },
    {
        id: 4,
        image: "https://rukminim1.flixcart.com/image/612/612/k63xle80/shoe/9/a/p/krf1133-7-kreuzer-black-original-imafeng3jwnrwgry.jpeg?q=70",
        brand: "Kirasa",
        price: "RS.499",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/kzhbfrk0/shoe/y/m/k/9-mrj1851-9-aadi-tan-original-imagbgnfvgdhwwc4.jpeg?q=70",
        brand: "aadi",
        price: "RS.399",
        description: "Formals for men",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/h/z/-original-imaggcaxwzpheakm.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "Oxford For Men",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/l4n2oi80/shoe/p/j/q/9-art-mn9-knight-walkers-brown-original-imagfh6nz3zyfsds.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "Synthetic Leather For Men",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/kxc5nrk0/shoe/g/n/q/8-mrj1796-8-aadi-black-original-imag9tcewzsbedmv.jpeg?q=70",
        brand: "aadi",
        price: "RS.359",
        description: "Formals for men",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/l/l/-original-imagfpz8fgbmwgzt-bb.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/9/u/rkm-10-feetway-black-original-imafpzunrvnbnhwd-bb.jpeg?q=70",
        brand: "Feetway",
        price: "RS.616",
        description: "Oxford For Men",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/g/k/6-54490051-6-liberty-black-original-imaghj7ecggwrjsb.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Formals for men",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/k3xcdjk0pkrrdj/shoe/4/h/c/8-orifwsh-1237-oricum-orifwsh-1237-original-imafgfuyxhhfczxx.jpeg?q=70",
        brand: "Bersache",
        price: "RS.438",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/a/m/n/-original-imagg6r9cqyhjvzw.jpeg?q=70",
        brand: "Bata",
        price: "RS.848",
        description: "Synthetic Leather For Men",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/i/e/-original-imaghvb57ftpkfxb.jpeg?q=70",
        brand: "Provogue",
        price: "RS.969",
        description: "Formals for men",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/k3dc7m80pkrrdj/shoe/q/a/m/6-mrj1303-aadi-original-imafhvrh2c8uxfgw.jpeg?q=70",
        brand: "aadi",
        price: "RS.499",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/kfwvcsw0-0/shoe/i/i/4/mrj1488-10-aadi-black-original-imafw9p38fqvmmmh.jpeg?q=70",
        brand: "aadi",
        price: "RS.329",
        description: "Synthetic Leather For Men",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/k4hcjgw0pkrrdj/shoe/8/j/5/7-orifwsh-3029-oricum-orifwsh-3029-original-imafj8sxft7g2gyh.jpeg?q=70",
        brand: "Oriculum",
        price: "RS.479",
        description: "Formals for men",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/5/i/z/-original-imagg6r4whwwphpu.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORMAL OFFICER CLASS SHOES S",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/kx3l0nk0/shoe/d/h/3/6-8214478-6-bata-brown-original-imag9mz3z722mvvt.jpeg?q=70",
        brand: "Bata",
        price: "RS.1349",
        description: "Formals for men",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/i/n/p/-original-imaggcaxf8g4hff3.jpeg?q=70",
        brand: "aadi",
        price: "RS.449",
        description: "Synthetic Leather For Men",
    },
]

const EthnicMen = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/x/8/-original-imagg7ek9cjf2tmz.jpeg?q=70",
        brand: "Vellinto",
        price: " RS.623",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/kg2l47k0-0/shoe/d/q/2/550w-6-baxxico-white-original-imafwdy5u7fdnm9j.jpeg?q=70",
        brand: "Yayab",
        price: "RS.899",
        description: "Mojaris For Men",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/t/i/-original-imaggdfegjgckdub.jpeg?q=70",
        brand: "Ryag",
        price: "RS.479",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 4,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/3/f/y/j3-7-sarthi-brown-original-imaf5s6axhqw6kgw-bb.jpeg?q=70",
        brand: "Shathi",
        price: "RS.499",
        description: "Royal and Traditional",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/0/v/8-art-ca306-vellinto-brown-original-imagka2ekenxw3y8.jpeg?q=70",
        brand: "Vellinto",
        price: "RS.399",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/l12h1u80/shoe/j/r/s/7-oak1-7-hyooo-brown-original-imagcpv7gzbrnzj4.jpeg?q=70",
        brand: "hyoo",
        price: "RS.799",
        description: "Ethnic Mule For Men",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/g/t/h/6-art-ca159-vellinto-tan-original-imagykfz57fyvkgk-bb.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/l5iid8w0/shoe/j/k/6/8-55800521-rockfield-brown-original-imagg62cakybybxk.jpeg?q=70",
        brand: "Rockfield",
        price: "RS.359",
        description: "Royal and Traditional",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/f/n/9-kv319-kavsun-brown-original-imagh2tqzbhvzqf5.jpeg?q=70",
        brand: "Kavsun",
        price: "RS.699",
        description: "Mojaris For Men",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/l19m93k0/shoe/p/k/z/9-white-chain-traditional-funda-white-original-imagcvc9unqvkw64.jpeg?q=70",
        brand: "Taditional Funda",
        price: "RS.499",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/o/t/-original-imagg4zgnumghec2.jpeg?q=70",
        brand: "Onivixo",
        price: "RS.499",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/i/l/-original-imaggjtrfhv5fjbq.jpeg?q=70",
        brand: "Krors",
        price: "RS.499",
        description: "Ethnic Mule For Men",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/v/q/6/-original-imagg3a8yppvrvhs.jpeg?q=70",
        brand: "Vellinto",
        price: "RS.623",
        description: "Mojaris For Men",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/ksyz8280/shoe/w/6/n/8-jalsa-jt38-8-jaipur-trendcraft-white-original-imag6eskx7ubpeq6.jpeg?q=70",
        brand: "Jaipur Trend Craft",
        price: "RS.369",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/l/n/-original-imagg7syze82egzu.jpeg?q=70",
        brand: "TR",
        price: "RS.479",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/l52sivk0/shoe/s/2/r/8-719-8-ovexa-tan-original-imagfu3mbhdyzpgn.jpeg?q=70",
        brand: "putul",
        price: "RS.499",
        description: "Mojaris For Men",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/3/4/4/1048-9-dev-fashion-hub-black-original-imaew7pfknkkdsxr-bb.jpeg?q=70",
        brand: "Prem",
        price: "RS.260",
        description: "Royal and Traditional",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/y/z/n/-original-imaghvbanp2nwjgj.jpeg?q=70",
        brand: "Jayman",
        price: "RS.299",
        description: "punjabi jutti , nagra , nagra shoes , kurta shoes , jut...",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/z/n/-original-imagg5qa7bcm83qm.jpeg?q=70",
        brand: "kavsun",
        price: "RS.699",
        description: "GVR CASUALS Jutis For MenBlack",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/j/3/7/6-yb587-6-6-yb-bazaar-beige-original-imaghafbghav9fyb.jpeg?q=70",
        brand: "YB Bazaar",
        price: "RS.299",
        description: "Mojaris For Men",
    },
]

export {men, CasualMen, FormalMen, EthnicMen };