const women = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/4/3/-original-imagh8zzeda7636t.jpeg?q=70",
        brand: "Adidas Originals",
        price: " RS.623",
        description: "SUPERSTAR W Sneakers For Women",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/h/q/4-124878-skechers-multicolor-original-imagg35brbhnmbmh.jpeg?q=70",
        brand: "Sketchers",
        price: "RS.899",
        description: "GO WALK ARCH FIT - DYNAMIC VI Sneakers For Women",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/ky7lci80/shoe/j/i/u/6-11009440-fila-blk-wht-original-imagahrffzuxfq2r.jpeg?q=70",
        brand: "Fila",
        price: "RS.479",
        description: "https://rukminim1.flixcart.com/image/612/612/ky7lci80/shoe/j/i/u/6-11009440-fila-blk-wht-original-imagahrffzuxfq2r.jpeg?q=70",
    },
    {
        id: 4,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61PBtPDh1VL._AC_UL320_.jpg",
        brand: "Shoesion",
        price: " RS.623",
        description: "Women's Stylish Comfortable Pull On Flat Loafer Ballet Casual &",
    },
    {
        id: 5,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/6139e1TT52L._AC_UL320_.jpg",
        brand: "Sezen",
        price: "RS.899",
        description: "Women's Faux Leather Comfortable Slip on Mules Sho",
    },
    {
        id: 6,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61WZXU1uB0L._AC_UL320_.jpg",
        brand: "FASHIMO",
        price: "RS.479",
        description: "Formal Casual Shoes for Women & Girl's.",
    },
    {
        id: 7,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61TF2DTkMGL._AC_UL320_.jpg",
        brand: "Meriggiarre",
        price: "RS.499",
        description: "OZELIA W Sneakers For Women",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/p/5/5-sf043-juttiwala-purple-original-imag4vtptmtq3rfw-bb.jpeg?q=70",
        brand: "Jutiwala",
        price: "RS.399",
        description: "Jutis for Women",
    },
    {
        id: 9,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51TCWqWSt-L._AC_UL320_.jpg",
        brand: "Generic",
        price: "RS.449",
        description: "Queenstep Ethnic Handmade Shimmery Mule for Women & Girl",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/r/i/7-rainbow-sone-belly-red-7-clorigs-red-original-imag4s8qvzmkehgd-bb.jpeg?q=70",
        brand: "Clogris",
        price: "RS.799",
        description: "Stylish And Party Wear Look Mojari",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/k/w/-original-imagj93pmgdnbhzf.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.499",
        description: "OZELIA W Sneakers For Women",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/z/w/6-sh3315-london-rag-black-original-imagkrwchqq9zvzv.jpeg?q=70",
        brand: "London Rag",
        price: "RS.399",
        description: "Black Magnolia Cushion Collared Lace Up Boots Boots For...",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/jubjte80/shoe/b/3/q/cg6253-4-adidas-originals-cblack-carbon-rawwht-original-imaffguzyqssvy5s.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.799",
        description: "NITE JOGGER W Sneakers For Women",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/y/o/q/8-sh3286-london-rag-brown-original-imagjwqfsuysgmww.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "Brown Espiree High Heeled Ankle Boots Boots For Women",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/d/1/-original-imagkqztzfgbxzda.jpeg?q=70",
        brand: "New-Balance",
        price: "RS.359",
        description: "Sneakers For Women",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/x/b/-original-imagh74f6uhwgfg5.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "Casuals For Women",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/jnj7iq80/shoe/z/n/g/b28152-5-adidas-originals-cblack-cblack-ftwwht-original-imafa4gsxhe6xmas.jpeg?q=70",
        brand: "Feetway",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Sneakers For Women",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/u/0/6-gw9754-6-adidas-originals-ftwwht-green-bliora-original-imagghtjfrxhsdxq.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "ADISUPER W Sneakers For Women  (White)",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/h/m/j/5-11010354-fila-ban-rug-original-imagjkhgd4vchxmj.jpeg?q=70",
        brand: "Fila",
        price: "RS.438",
        description: "Fila Womens F14 Pink",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/p/l/a/5-gx0417-adidas-originals-cblack-cblack-ftwwht-original-imaghdv36hx83kp7.jpeg?q=70",
        brand: "Bata",
        price: "RS.848",
        description: "ZENTIC W Sneakers For Women",
    },
    {
        id: 21,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/u/l/4-95453-717-k-swiss-bright-gold-marshmallow-original-imaghxpjng67jpn7.jpeg?q=70",
        brand: "K-Swiss",
        price: "RS.969",
        description: "K-Swiss Synthetic & Mesh Multicoloured Women Casual Sneakers",
    },
    {
        id: 22,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/e/4/6-gx2047-6-adidas-originals-ftwwht-almpnk-beamgr-original-imagghtuatvqdhqs.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.499",
        description: "STAN SMITH W Sneakers For Women  (White)",
    },
    {
        id: 23,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/610SbLdIRuL._AC_UL320_.jpg",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Formals for Women",
    },
    {
        id: 24,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51xdTrVdP7L._AC_UL320_.jpg",
        brand: "zoyi",
        price: "RS.438",
        description: "Women's Leather Slip on Mules; Block Heel Casual and Formal,"
    },
    {
        id: 25,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71GrTho7-YL._AC_UL320_.jpg",
        brand: "Ryzon",
        price: "RS.848",
        description: "Stylish Velvet Shoes for Girls and Women for Casual Wear And",
    },
    {
        id: 26,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61R-TV1b3DL._AC_UL320_.jpg",
        brand: "K-Swiss",
        price: "RS.969",
        description: "Beauty Formals For Women",
    },
    {
        id: 27,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61JLgG2sRBL._AC_UL320_.jpg",
        brand: "CraftNCreation",
        price: "RS.499",
        description: "Women Comfortable Loafer Mules Ballet Wedge Heels Footwear",
    },
    {
        id: 28,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71iiHw-rRZL._AC_UL320_.jpg",
        brand: "Stain-G",
        price: "RS.329",
        description: "Women Golden Multi Ethnic Embellished Block Heels Mules",
    },
    {
        id: 29,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41xtneHWXbL._AC_UL320_.jpg",
        brand: "Fila",
        price: "RS.479",
        description: "Rajasthan Crafts House Ethnic Mules for Women and Girls",
    },
    {
        id: 30,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61H7qjeDG8L._AC_UL320_.jpg",
        brand: "Biba",
        price: "RS.799",
        description: "Women's Black Mules",
    },
    {
        id: 31,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51JJG3wWxXL._AC_UL320_.jpg",
        brand: "Commander",
        price: "RS.1349",
        description: "Latest Women Stylish Bellies",
    },
    {
        id: 32,
        image: "https://rukminim1.flixcart.com/image/612/612/kxuqdu80/shoe/d/v/m/4-sg-f-794-37-saint-g-black-original-imaga7phqbcazahx.jpeg?q=70",
        brand: "Stain-G",
        price: "RS.329",
        description: "Black Color Women Leather Ankle Boot Boots For Women",
    },
    {
        id: 33,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/z/o/4-11010313-fila-bfh-atm-blu-original-imaggdy9hf9t4g4c.jpeg?q=70",
        brand: "Fila",
        price: "RS.479",
        description: "Fila Womens RENNO",
    },
    {
        id: 34,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/x/h/5-gy9556-adidas-originals-ftwwht-owhite-powred-original-imaghdvfryk4kfqz.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORUM MID W Sneakers For Wo",
    },
    {
        id: 35,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/n/b/q/6-5-16274252-nike-beige-original-imaghzrfygrhzqfq.jpeg?q=70",
        brand: "Nike",
        price: "RS.1349",
        description: "Nike Women Beige Air Max Pre-Day Sneakers Brogues For W...",
    },
    {
        id: 36,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/x/q/7-gx2074-adidas-originals-cblack-almyel-powred-original-imaghdv2sqdhwdcy.jpeg?q=70",
        brand: "Adidas",
        price: "RS.449",
        description: "NMD_R1 W Sneakers For Women  (Black)",
    },
    {
        id:37,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61pqLOZPruL._AC_UL320_.jpg",
        brand: "Shoesion",
        price: "RS.499",
        description: "Women's Stylish Comfortable Pull On Flat Embossing Loafer Ballet",
    },
    {
        id: 38,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61U9l8+S3KL._AC_UL320_.jpg",
        brand: "Marc Loire",
        price: "RS.399",
        description: "Women Comfortable Slip On Flat Loafer Ballet; Casual and Formal",
    },
    {
        id: 39,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61XhRbhBE0L._AC_UL320_.jpg",
        brand: "Marc Loire",
        price: "RS.799",
        description: "Women's Faux Leather Comfortable Slip on Mules Shoes",
    },
    {
        id: 40,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61ifyw8p12L._AC_UL320_.jpg",
        brand: "MK Craft",
        price: "RS.664",
        description: "Women Comfortable Metallic Loafer Mules Wedges Casual &",
    },
    {
        id: 41,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61fdBu5AJsL._AC_UL320_.jpg",
        brand: "Adjoin-Step",
        price: "RS.359",
        description: "Black Formal Belly for Women/Black Loafers Slipon for",
    },
    {
        id: 42,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61vrOAeqd0L._AC_UL320_.jpg",
        brand: "Zoyi",
        price: "RS.799",
        description: "Stylish And Trendy Formal Embroi",
    },
    {
        id: 43,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61G-FDjLC5L._AC_UL320_.jpg",
        brand: "Beauty Walk",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Formals For Women",
    },
    {
        id: 44,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71CrrmwXjNL._AC_UL320_.jpg",
        brand: "Stain-G",
        price: "RS.329",
        description: "Women Golden Multi Formal Embellished Block Heels Mules",
    },
    {
        id: 45,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51Tnr8AljbL._AC_UL320_.jpg",
        brand: "Ladies Hub",
        price: "RS.479",
        description: "Comfortable Women's Slip-on Casual Mules Shoes & Sandals",
    },
    {
        id: 46,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71iLndmNWEL._AC_UL320_.jpg",
        brand: "Bata",
        price: "RS.799",
        description: "Womens Felice Espadrilles",
    },
    {
        id: 47,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61MoJpV4IuL._AC_UL320_.jpg",
        brand: "Clarks",
        price: "RS.1349",
        description: "Hamble Loafer Black Leather",
    },
    {
        id: 48,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/e/m/f/stp-8-toshina-shoes-king-red-original-imafngruazqfbg2x-bb.jpeg?q=70",
        brand: "Toshina Shoe King",
        price: "RS.449",
        description: "Wedges Slip On For Women",
    },
    {
        id: 49,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/6/z/-original-imaghxfgge47rgsk.jpeg?q=70",
        brand: "Shoe-Topia",
        price: " RS.623",
        description: "Women & Girls Ethnic Fashion Sandal Mules W Sneakers For Women",
    },
    {
        id: 50,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/611w+F966kL._AC_UL320_.jpg",
        brand: "Sezen",
        price: "RS.899",
        description: "GO WATextile Fabric Floral Print Designer Fashionable Mules for Girls andLK ARCH FIT - DYNAMIC VI Sneakers For Women",
    },
    {
        id: 51,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51OV3l3PWFL._AC_UL320_.jpg",
        brand: "V S-1 Fashion Mode",
        price: "RS.479",
        description: "Ethnic Casual Shoes for Women & Girl's.",
    },
    {
        id: 52,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/r/p/c/8-wehite-gulaab-belly-8-mk-craft-white-original-imag9ys9f3cghnyu-bb.jpeg?q=70",
        brand: "MK Craft",
        price: "RS.664",
        description: "Jutis for Women",
    },
    {
        id: 53,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/h/u/i/-original-imaghxfbcmvwdyzx.jpeg?q=70",
        brand: "Ziyarat-Collection",
        price: "RS.359",
        description: "Jutis For Women",
    },
    {
        id: 54,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/b/e/t/-original-imagg892uk322bqq-bb.jpeg?q=70",
        brand: "Zoyi",
        price: "RS.799",
        description: "Stylish And Trendy Ethnic Embroi",
    },
    {
        id: 55,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/w/u/-original-imagg3m89txkhw7r.jpeg?q=70",
        brand: "Beauty Walk",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Sneakers For Women",
    },
    {
        id: 56,
        image: "https://rukminim1.flixcart.com/image/832/832/kzblocw0/shoe/r/z/f/9-kanti-aas-creation-blue-original-imagbd6nh5aegenm.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Jutis for Women",
    },
    {
        id: 57,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/0/i/d/-original-imagg6ybadhhe8v2-bb.jpeg?q=70",
        brand: "zoyi",
        price: "RS.438",
        description: "Girls Stylish Designer Jaipuri Rajasthani Mojari Bellie...,"
    },
    {
        id: 58,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/b/l/h/-original-imagg3m7adbfmtcb.jpeg?q=70",
        brand: "Ryzon",
        price: "RS.848",
        description: "Jutis for Women",
    },
    {
        id: 59,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/q/u/beads-juti-7-beauty-walk-pink-original-imafugyyauecemuf-bb.jpeg?q=70",
        brand: "K-Swiss",
        price: "RS.969",
        description: "Beauty WalkJutis For Women",
    },
    {
        id: 60,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/6/z/-original-imaghxfgge47rgsk.jpeg?q=70",
        brand: "CraftNCreation",
        price: "RS.499",
        description: "STAN SMITH W  For Women  (White)",
    },
]

const CasualWomen = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/z/4/3/-original-imagh8zzeda7636t.jpeg?q=70",
        brand: "Adidas Originals",
        price: " RS.623",
        description: "SUPERSTAR W Sneakers For Women",
    },
    {
        id: 2,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/s/h/q/4-124878-skechers-multicolor-original-imagg35brbhnmbmh.jpeg?q=70",
        brand: "Sketchers",
        price: "RS.899",
        description: "GO WALK ARCH FIT - DYNAMIC VI Sneakers For Women",
    },
    {
        id: 3,
        image: "https://rukminim1.flixcart.com/image/612/612/ky7lci80/shoe/j/i/u/6-11009440-fila-blk-wht-original-imagahrffzuxfq2r.jpeg?q=70",
        brand: "Fila",
        price: "RS.479",
        description: "https://rukminim1.flixcart.com/image/612/612/ky7lci80/shoe/j/i/u/6-11009440-fila-blk-wht-original-imagahrffzuxfq2r.jpeg?q=70",
    },
    {
        id: 4,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/k/w/-original-imagj93pmgdnbhzf.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.499",
        description: "OZELIA W Sneakers For Women",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/z/w/6-sh3315-london-rag-black-original-imagkrwchqq9zvzv.jpeg?q=70",
        brand: "London Rag",
        price: "RS.399",
        description: "Black Magnolia Cushion Collared Lace Up Boots Boots For...",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/jubjte80/shoe/b/3/q/cg6253-4-adidas-originals-cblack-carbon-rawwht-original-imaffguzyqssvy5s.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.799",
        description: "NITE JOGGER W Sneakers For Women",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/y/o/q/8-sh3286-london-rag-brown-original-imagjwqfsuysgmww.jpeg?q=70",
        brand: "Knight Walkers",
        price: "RS.664",
        description: "Brown Espiree High Heeled Ankle Boots Boots For Women",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/m/d/1/-original-imagkqztzfgbxzda.jpeg?q=70",
        brand: "New-Balance",
        price: "RS.359",
        description: "Sneakers For Women",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/x/b/-original-imagh74f6uhwgfg5.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "Casuals For Women",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/jnj7iq80/shoe/z/n/g/b28152-5-adidas-originals-cblack-cblack-ftwwht-original-imafa4gsxhe6xmas.jpeg?q=70",
        brand: "Feetway",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Sneakers For Women",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/x/u/0/6-gw9754-6-adidas-originals-ftwwht-green-bliora-original-imagghtjfrxhsdxq.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "ADISUPER W Sneakers For Women  (White)",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/h/m/j/5-11010354-fila-ban-rug-original-imagjkhgd4vchxmj.jpeg?q=70",
        brand: "Fila",
        price: "RS.438",
        description: "Fila Womens F14 Pink",
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/p/l/a/5-gx0417-adidas-originals-cblack-cblack-ftwwht-original-imaghdv36hx83kp7.jpeg?q=70",
        brand: "Bata",
        price: "RS.848",
        description: "ZENTIC W Sneakers For Women",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/w/u/l/4-95453-717-k-swiss-bright-gold-marshmallow-original-imaghxpjng67jpn7.jpeg?q=70",
        brand: "K-Swiss",
        price: "RS.969",
        description: "K-Swiss Synthetic & Mesh Multicoloured Women Casual Sneakers",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/e/4/6-gx2047-6-adidas-originals-ftwwht-almpnk-beamgr-original-imagghtuatvqdhqs.jpeg?q=70",
        brand: "Adidas Originals",
        price: "RS.499",
        description: "STAN SMITH W Sneakers For Women  (White)",
    },
    {
        id: 16,
        image: "https://rukminim1.flixcart.com/image/612/612/kxuqdu80/shoe/d/v/m/4-sg-f-794-37-saint-g-black-original-imaga7phqbcazahx.jpeg?q=70",
        brand: "Stain-G",
        price: "RS.329",
        description: "Black Color Women Leather Ankle Boot Boots For Women",
    },
    {
        id: 17,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/z/o/4-11010313-fila-bfh-atm-blu-original-imaggdy9hf9t4g4c.jpeg?q=70",
        brand: "Fila",
        price: "RS.479",
        description: "Fila Womens RENNO",
    },
    {
        id: 18,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/t/x/h/5-gy9556-adidas-originals-ftwwht-owhite-powred-original-imaghdvfryk4kfqz.jpeg?q=70",
        brand: "Bata",
        price: "RS.799",
        description: "FORUM MID W Sneakers For Wo",
    },
    {
        id: 19,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/n/b/q/6-5-16274252-nike-beige-original-imaghzrfygrhzqfq.jpeg?q=70",
        brand: "Nike",
        price: "RS.1349",
        description: "Nike Women Beige Air Max Pre-Day Sneakers Brogues For W...",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/x/q/7-gx2074-adidas-originals-cblack-almyel-powred-original-imaghdv2sqdhwdcy.jpeg?q=70",
        brand: "Adidas",
        price: "RS.449",
        description: "NMD_R1 W Sneakers For Women  (Black)",
    },
]

const FormalWomen = [
    {
        id: 1,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61PBtPDh1VL._AC_UL320_.jpg",
        brand: "Shoesion",
        price: " RS.623",
        description: "Women's Stylish Comfortable Pull On Flat Loafer Ballet Casual &",
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/6139e1TT52L._AC_UL320_.jpg",
        brand: "Sezen",
        price: "RS.899",
        description: "Women's Faux Leather Comfortable Slip on Mules Sho",
    },
    {
        id: 3,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61WZXU1uB0L._AC_UL320_.jpg",
        brand: "FASHIMO",
        price: "RS.479",
        description: "Formal Casual Shoes for Women & Girl's.",
    },
    {
        id: 4,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61pqLOZPruL._AC_UL320_.jpg",
        brand: "Shoesion",
        price: "RS.499",
        description: "Women's Stylish Comfortable Pull On Flat Embossing Loafer Ballet",
    },
    {
        id: 5,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61U9l8+S3KL._AC_UL320_.jpg",
        brand: "Marc Loire",
        price: "RS.399",
        description: "Women Comfortable Slip On Flat Loafer Ballet; Casual and Formal",
    },
    {
        id: 6,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61XhRbhBE0L._AC_UL320_.jpg",
        brand: "Marc Loire",
        price: "RS.799",
        description: "Women's Faux Leather Comfortable Slip on Mules Shoes",
    },
    {
        id: 7,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61ifyw8p12L._AC_UL320_.jpg",
        brand: "MK Craft",
        price: "RS.664",
        description: "Women Comfortable Metallic Loafer Mules Wedges Casual &",
    },
    {
        id: 8,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61fdBu5AJsL._AC_UL320_.jpg",
        brand: "Adjoin-Step",
        price: "RS.359",
        description: "Black Formal Belly for Women/Black Loafers Slipon for",
    },
    {
        id: 9,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61vrOAeqd0L._AC_UL320_.jpg",
        brand: "Zoyi",
        price: "RS.799",
        description: "Stylish And Trendy Formal Embroi",
    },
    {
        id: 10,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61G-FDjLC5L._AC_UL320_.jpg",
        brand: "Beauty Walk",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Formals For Women",
    },
    {
        id: 11,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/610SbLdIRuL._AC_UL320_.jpg",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Formals for Women",
    },
    {
        id: 12,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51xdTrVdP7L._AC_UL320_.jpg",
        brand: "zoyi",
        price: "RS.438",
        description: "Women's Leather Slip on Mules; Block Heel Casual and Formal,"
    },
    {
        id: 13,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71GrTho7-YL._AC_UL320_.jpg",
        brand: "Ryzon",
        price: "RS.848",
        description: "Stylish Velvet Shoes for Girls and Women for Casual Wear And",
    },
    {
        id: 14,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61R-TV1b3DL._AC_UL320_.jpg",
        brand: "K-Swiss",
        price: "RS.969",
        description: "Beauty Formals For Women",
    },
    {
        id: 15,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61JLgG2sRBL._AC_UL320_.jpg",
        brand: "CraftNCreation",
        price: "RS.499",
        description: "Women Comfortable Loafer Mules Ballet Wedge Heels Footwear",
    },
    {
        id: 16,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71CrrmwXjNL._AC_UL320_.jpg",
        brand: "Stain-G",
        price: "RS.329",
        description: "Women Golden Multi Formal Embellished Block Heels Mules",
    },
    {
        id: 17,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51Tnr8AljbL._AC_UL320_.jpg",
        brand: "Ladies Hub",
        price: "RS.479",
        description: "Comfortable Women's Slip-on Casual Mules Shoes & Sandals",
    },
    {
        id: 18,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71iLndmNWEL._AC_UL320_.jpg",
        brand: "Bata",
        price: "RS.799",
        description: "Womens Felice Espadrilles",
    },
    {
        id: 19,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61MoJpV4IuL._AC_UL320_.jpg",
        brand: "Clarks",
        price: "RS.1349",
        description: "Hamble Loafer Black Leather",
    },
    {
        id: 20,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/e/m/f/stp-8-toshina-shoes-king-red-original-imafngruazqfbg2x-bb.jpeg?q=70",
        brand: "Toshina Shoe King",
        price: "RS.449",
        description: "Wedges Slip On For Women",
    },
]

const EthnicWomen = [
    {
        id: 1,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/6/z/-original-imaghxfgge47rgsk.jpeg?q=70",
        brand: "Shoe-Topia",
        price: " RS.623",
        description: "Women & Girls Ethnic Fashion Sandal Mules W Sneakers For Women",
    },
    {
        id: 2,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/611w+F966kL._AC_UL320_.jpg",
        brand: "Sezen",
        price: "RS.899",
        description: "GO WATextile Fabric Floral Print Designer Fashionable Mules for Girls andLK ARCH FIT - DYNAMIC VI Sneakers For Women",
    },
    {
        id: 3,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51OV3l3PWFL._AC_UL320_.jpg",
        brand: "V S-1 Fashion Mode",
        price: "RS.479",
        description: "Ethnic Casual Shoes for Women & Girl's.",
    },
    {
        id: 4,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61TF2DTkMGL._AC_UL320_.jpg",
        brand: "Meriggiarre",
        price: "RS.499",
        description: "OZELIA W Sneakers For Women",
    },
    {
        id: 5,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/o/p/5/5-sf043-juttiwala-purple-original-imag4vtptmtq3rfw-bb.jpeg?q=70",
        brand: "Jutiwala",
        price: "RS.399",
        description: "Jutis for Women",
    },
    {
        id: 6,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/c/r/i/7-rainbow-sone-belly-red-7-clorigs-red-original-imag4s8qvzmkehgd-bb.jpeg?q=70",
        brand: "Clogris",
        price: "RS.799",
        description: "Stylish And Party Wear Look Mojari",
    },
    {
        id: 7,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/r/p/c/8-wehite-gulaab-belly-8-mk-craft-white-original-imag9ys9f3cghnyu-bb.jpeg?q=70",
        brand: "MK Craft",
        price: "RS.664",
        description: "Jutis for Women",
    },
    {
        id: 8,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/h/u/i/-original-imaghxfbcmvwdyzx.jpeg?q=70",
        brand: "Ziyarat-Collection",
        price: "RS.359",
        description: "Jutis For Women",
    },
    {
        id: 9,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/b/e/t/-original-imagg892uk322bqq-bb.jpeg?q=70",
        brand: "Zoyi",
        price: "RS.799",
        description: "Stylish And Trendy Ethnic Embroi",
    },
    {
        id: 10,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/4/w/u/-original-imagg3m89txkhw7r.jpeg?q=70",
        brand: "Beauty Walk",
        price: "RS.616",
        description: "STAN SMITH NEW BOLD W Sneakers For Women",
    },
    {
        id: 11,
        image: "https://rukminim1.flixcart.com/image/832/832/kzblocw0/shoe/r/z/f/9-kanti-aas-creation-blue-original-imagbd6nh5aegenm.jpeg?q=70",
        brand: "Liberty Rob",
        price: "RS.999",
        description: "Jutis for Women",
    },
    {
        id: 12,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/0/i/d/-original-imagg6ybadhhe8v2-bb.jpeg?q=70",
        brand: "zoyi",
        price: "RS.438",
        description: "Girls Stylish Designer Jaipuri Rajasthani Mojari Bellie...,"
    },
    {
        id: 13,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/b/l/h/-original-imagg3m7adbfmtcb.jpeg?q=70",
        brand: "Ryzon",
        price: "RS.848",
        description: "Jutis for Women",
    },
    {
        id: 14,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/d/q/u/beads-juti-7-beauty-walk-pink-original-imafugyyauecemuf-bb.jpeg?q=70",
        brand: "K-Swiss",
        price: "RS.969",
        description: "Beauty WalkJutis For Women",
    },
    {
        id: 15,
        image: "https://rukminim1.flixcart.com/image/612/612/xif0q/shoe/f/6/z/-original-imaghxfgge47rgsk.jpeg?q=70",
        brand: "CraftNCreation",
        price: "RS.499",
        description: "STAN SMITH W  For Women  (White)",
    },
    {
        id: 16,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/71iiHw-rRZL._AC_UL320_.jpg",
        brand: "Stain-G",
        price: "RS.329",
        description: "Women Golden Multi Ethnic Embellished Block Heels Mules",
    },
    {
        id: 17,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/41xtneHWXbL._AC_UL320_.jpg",
        brand: "Fila",
        price: "RS.479",
        description: "Rajasthan Crafts House Ethnic Mules for Women and Girls",
    },
    {
        id: 18,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/61H7qjeDG8L._AC_UL320_.jpg",
        brand: "Biba",
        price: "RS.799",
        description: "Women's Black Mules",
    },
    {
        id: 19,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51JJG3wWxXL._AC_UL320_.jpg",
        brand: "Commander",
        price: "RS.1349",
        description: "Latest Women Stylish Bellies",
    },
    {
        id: 20,
        image: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/51TCWqWSt-L._AC_UL320_.jpg",
        brand: "Generic",
        price: "RS.449",
        description: "Queenstep Ethnic Handmade Shimmery Mule for Women & Girl",
    },
]

export { women, CasualWomen, FormalWomen, EthnicWomen };